server:
  port: ${SERVER_APP_PORT:8080}
spring:
  main:
    banner-mode: "off"
  datasource:
    schema: public
    url: jdbc:postgresql://${DB_CONNECTION_IP:postgres}:${DB_CONNECTION_PORT:5432}/penpixel_db
    username: ${POSTGRES_USER:user123}
    password: ${POSTGRES_PASSWORD:pass123}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: WriteHikariPool
      schema: public
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 30000
      repositories:
        enabled: false
  cache:
    type: redis
    redis:
      time-to-live: 10s
  messages:
    basename: messages,config.i18n.messages
    encoding: UTF-8
  devtools:
    restart:
      enabled: false
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
data:
  repository:
    pageSize: 10
app:
  cache:
    ttl: 10